# Generated by Django 5.2.1 on 2025-07-06 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='asset',
            field=models.ImageField(blank=True, null=True, upload_to='event_asset'),
        ),
    ]
