# Generated by Django 5.2.1 on 2025-07-06 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_asset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='asset',
        ),
    ]
