# Generated by Django 5.2.1 on 2025-07-06 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_remove_event_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='asset',
            field=models.ImageField(blank=True, default='event_asset/default_img.jpg', null=True, upload_to='event_asset'),
        ),
    ]
